const express				= require('express')
const authMiddleware		= require('../../middleware/auth')
const authControllers		= require('../../controllers/authController')
const router				= express.Router()
router.post('/login',		authControllers.login)
router.post('/logout',		authControllers.logout)
router.post('/refresh',		authControllers.refresh)
router.post('/register',	authControllers.register)
router.get('/user',			authMiddleware, authControllers.user)
router.get('/user/:id',		authControllers.getUserById)
module.exports				= router